# Generated by Django 5.2.3 on 2025-07-24 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='hire_data',
            new_name='hire_date',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='salry',
            new_name='salary',
        ),
    ]
